### ISSUE TITLE
The Bug of  Http url mixed Chinese character

### ISSUE THREAD

**Issue by RyanLiuF** [lincolnloop/python-qrcode#193]
```
import qrcode
qr = qrcode.QRCode(   
  version=1,   
  error_correction=qrcode.constants.ERROR_CORRECT_L,   
  box_size=20,   
  border=4, 
) 
qr.add_data('http://127.0.0.1/file/economic/现代方法.pdf') 
qr.make(fit=True) 
img = qr.make_image()
img.save('test.png')
```
If the url is 'http://127.0.0.1/file/economic/现代方法.pdf', then the scanned image data is 'http://127.0.0.1/file/economic/.pdf'. But if the url is 'http:/127.0.0.1/file/economic/现代方法.pdf', the result is OK. Please fixed it.

**Comment by heuer** [comment]
Is the missing slash after the http scheme in the 2nd URL intentional?

Using your code above results into the following QR Code
![test](https://user-images.githubusercontent.com/364926/76681164-40169680-65f0-11ea-80fa-2d2af14b1758.png)

Decoding seems to be fine
![test-decoded](https://user-images.githubusercontent.com/364926/76681171-4c025880-65f0-11ea-8743-5e8b3c4b28ad.png)

**Comment by RyanLiuF** [comment]
But I use the wechat app to scan the image , the result is "http://127.0.0.1/file/economic/.pdf". Seems that the app makes mistake ??

**Comment by nayuki** [comment]
I believe you are not allowed to put Unicode characters into URLs. You should UTF-8 encode them and then percent-encode them, like this: `http://127.0.0.1/file/economic/%E7%8E%B0%E4%BB%A3%E6%96%B9%E6%B3%95.pdf`
