### ISSUE TITLE
Convert to data URI

### ISSUE THREAD

**Issue by EricOuma** [lincolnloop/python-qrcode#222]
```
import qrcode
img = qrcode.make('Some data here')
```
Any leads on how I can convert the img object returned here to a data uri
NB: I don't want to save the image to a file.

**Comment by EmperorArthur** [comment]
# Answer

Data URLs are described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).  The trick is to write the image data to a buffer instead of a real file.

```python
import qrcode
from io import BytesIO
from base64 import b64encode

buffer = BytesIO()
img = qrcode.make('Some data here')
img.save(buffer)
encoded_img = b64encode(buffer.getvalue()).decode()

data_uri = "data:image/png;base64,{}".format(encoded_img)
```

`data_uri` has the value you want.  Note that `b64encode` returns bytes, so `decode()` was used to convert it to a string.
